### ISSUE TITLE
When doing an upload, the following error is encountered

### ISSUE THREAD

**Issue by barrychapman** [page7/wp_upload_rename#1]
Note, this was for a multiple file upload into ML. Not attaching something to a post:

( ! ) Warning: Missing argument 4 for wp_upload_rename::_name(), called in /var/www/html/new/html/wp-content/plugins/wp-upload-rename/wp_upload_rename.php on line 134 and defined in /var/www/html/new/html/wp-content/plugins/wp-upload-rename/wp_upload_rename.php on line 87

**Comment by page7** [comment]
Thx ~ :+1:
